[tool.poetry]
name = "project13"
version = "0.1.0"
description = ""
authors = ["Dmitry <process@proengineering.su>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
